% CED_SS_Train.m
% =========================================================================
% CED (Coupled Electric Drives) state-space model training with order sweep.
% Reproduces the System Identification app estimation exactly:
%   Options = n4sidOptions;
%   Options.Focus = 'simulation';
%   model = n4sid(mydata, order, 'Form', 'free', 'Ts', 0, Options);
%
% Input : CED_processed.mat (generated by CED_data_process.m, division
%         identical to the Python Option.py: train = first 200 samples of
%         each of the two amplitude segments, concatenated low-then-high),
%         containing CED_X_train [1 x 400] and CED_Y_train [1 x 400]
%         (single channel, fs = 50 Hz, Ts = 0.02 s).
% Output: one model per order, saved to ./SS_CED_Model/ss<order>_CED.mat
%
% Requires: System Identification Toolbox
% Note: n4sid is deterministic, so identical configuration reproduces the
%       GUI estimation results exactly.
% =========================================================================

scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, '..', 'Data', 'CED_processed.mat');
S = load(dataFile);

U = S.CED_X_train';    % [400 x 1] (low-amplitude segment 200 + high-amplitude segment 200)
Y = S.CED_Y_train';    % [400 x 1]
Ts_sample = 0.02;      % CED sampling interval (s): 1/fs, fs=50 Hz
mydata = iddata(Y, U, Ts_sample);

saveDir = fullfile(scriptDir, 'SS_CED_Model');
if ~exist(saveDir, 'dir')
    mkdir(saveDir);
end

orders = 1:10;

for o = orders
    Options = n4sidOptions;
    Options.Display = 'on';
    Options.Focus = 'simulation';
    model = n4sid(mydata, o, 'Form', 'free', 'Ts', 0, Options);
    save(fullfile(saveDir, sprintf('ss%d_CED.mat', o)), 'model');
end
