% CT_SS_Train.m
% =========================================================================
% CT (Cascaded Tanks) state-space model training with order sweep.
% Reproduces the System Identification app estimation exactly:
%   Options = n4sidOptions;
%   Options.Focus = 'simulation';
%   model = n4sid(mydata, order, 'Form', 'free', 'Ts', 0, Options);
%
% Input : CT_processed.mat (generated by CT_data_process.m), containing
%         CT_X_train [1 x 700] and CT_Y_train [1 x 700] (single channel,
%         sampling frequency fs = 0.25 Hz, Ts = 4 s).
% Output: one model per order, saved to ./SS_CT_Model/ss<order>_CT.mat
%
% Requires: System Identification Toolbox
% Note: n4sid is deterministic, so identical configuration reproduces the
%       GUI estimation results exactly.
% =========================================================================

scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, '..', 'Data', 'CT_processed.mat');
S = load(dataFile);

U = S.CT_X_train';    % [700 x 1]
Y = S.CT_Y_train';    % [700 x 1]
Ts_sample = 4;        % CT sampling interval (s): 1/fs, fs=0.25 Hz (Python / CT.mat Ts field)
mydata = iddata(Y, U, Ts_sample);

saveDir = fullfile(scriptDir, 'SS_CT_Model');
if ~exist(saveDir, 'dir')
    mkdir(saveDir);
end

orders = 1:10;

for o = orders
    Options = n4sidOptions;
    Options.Display = 'on';
    Options.Focus = 'simulation';
    model = n4sid(mydata, o, 'Form', 'free', 'Ts', 0, Options);
    save(fullfile(saveDir, sprintf('ss%d_CT.mat', o)), 'model');
end
