% SB_SS_Train.m
% =========================================================================
% SB (Silver Box) state-space model training with order sweep.
% Reproduces the System Identification app estimation exactly:
%   Options = n4sidOptions;
%   Options.Focus = 'simulation';
%   model = n4sid(mydata, order, 'Form', 'free', 'Ts', 0, Options);
%
% Input : SB_processed.mat (generated by SB_data_process.m), containing
%         SB_X_train [1 x 32531] and SB_Y_train [1 x 32531] (single
%         channel; sampling time set to Ts = 1, consistent with the
%         System Identification app / calculate_SB.m).
% Output: one model per order, saved to ./SS_SB_Model/ss<order>_SB.mat
%
% Requires: System Identification Toolbox
% Note: n4sid is deterministic, so identical configuration reproduces the
%       GUI estimation results exactly.
% =========================================================================

scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, '..', 'Data', 'SB_processed.mat');
S = load(dataFile);

U = S.SB_X_train';    % [32531 x 1]
Y = S.SB_Y_train';    % [32531 x 1]
Ts_sample = 1/610.35; % SB sampling interval (s): 1/fs, fs=610.35 Hz
mydata = iddata(Y, U, Ts_sample);

saveDir = fullfile(scriptDir, 'SS_SB_Model');
if ~exist(saveDir, 'dir')
    mkdir(saveDir);
end

orders = 1:10;

for o = orders
    Options = n4sidOptions;
    Options.Display = 'on';
    Options.Focus = 'simulation';
    model = n4sid(mydata, o, 'Form', 'free', 'Ts', 0, Options);
    save(fullfile(saveDir, sprintf('ss%d_SB.mat', o)), 'model');
end
