% CED_NARX_Train.m
% =========================================================================
% CED (Coupled Electric Drives) NARX training with 5 random seeds.
% Reproduces the Neural Time Series app workflow exactly:
%   narxnet(1:10, 1:10, 10, 'open', 'trainlm'), 70/15/15 data division,
%   rng(seed) fixes both weight initialization and data division.
% Training parameters are left at toolbox defaults so that the reported
% results are reproduced verbatim. The network is trained purely in open
% loop (no closed-loop fine-tuning).
%
% Input : CED_processed.mat (generated by CED_data_process.m, division
%         identical to the Python Option.py: train = first 200 samples of
%         each of the two amplitude segments, concatenated low-then-high),
%         containing CED_X_train [1 x 400] and CED_Y_train [1 x 400].
% Output: one network per seed, saved to
%         ./NARX_CED_Model/CED_NARX_seed<seed>.mat with top-level variable
%         CED_NARX_seed<seed> (.Network + .TrainingResults, GUI export
%         convention).
%
% Requires: Deep Learning Toolbox
% =========================================================================

scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, '..', 'Data', 'CED_processed.mat');
S = load(dataFile);

CED_X_train = S.CED_X_train;     % [1 x 400]
CED_Y_train = S.CED_Y_train;     % [1 x 400]

SEEDS = [9 66 108 88 52];

X = tonndata(CED_X_train, true, false);
T = tonndata(CED_Y_train, true, false);

saveDir = fullfile(scriptDir, 'NARX_CED_Model');
if ~exist(saveDir, 'dir')
    mkdir(saveDir);
end

for s = SEEDS
    fprintf('\n========== CED NARX seed=%d ==========\n', s);
    rng(s);                          % fix weight initialization + data division

    net = narxnet(1:10, 1:10, 10, 'open', 'trainlm');
    [x, xi, ai, t] = preparets(net, X, {}, T);
    net.divideParam.trainRatio = 70/100;
    net.divideParam.valRatio   = 15/100;
    net.divideParam.testRatio  = 15/100;
    [net, tr] = train(net, x, t, xi, ai);

    varname = sprintf('CED_NARX_seed%d', s);
    S2.(varname) = struct('Network', net, 'TrainingResults', tr);
    save(fullfile(saveDir, sprintf('CED_NARX_seed%d.mat', s)), '-struct', 'S2');
    S2 = struct();
end
