% CT_NARX_Train.m
% =========================================================================
% CT (Cascaded Tanks) NARX training with 5 random seeds.
% Reproduces the Neural Time Series app workflow exactly:
%   narxnet(1:10, 1:10, 10, 'open', 'trainlm'), 70/15/15 data division,
%   rng(seed) fixes both weight initialization and data division.
% Training parameters are left at toolbox defaults so that the reported
% results are reproduced verbatim. The network is trained purely in open
% loop (no closed-loop fine-tuning).
%
% Input : CT_processed.mat (generated by CT_data_process.m), containing
%         CT_X_train [1 x 700] and CT_Y_train [1 x 700].
% Output: one network per seed, saved to
%         ./NARX_CT_Model/CT_NARX_seed<seed>.mat with top-level variable
%         CT_NARX_seed<seed> (.Network + .TrainingResults, GUI export
%         convention).
%
% Requires: Deep Learning Toolbox
% =========================================================================

scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, '..', 'Data', 'CT_processed.mat');
S = load(dataFile);

CT_X_train = S.CT_X_train;     % [1 x 700]
CT_Y_train = S.CT_Y_train;     % [1 x 700]

SEEDS = [9 66 108 88 52];

X = tonndata(CT_X_train, true, false);
T = tonndata(CT_Y_train, true, false);

saveDir = fullfile(scriptDir, 'NARX_CT_Model');
if ~exist(saveDir, 'dir')
    mkdir(saveDir);
end

for s = SEEDS
    fprintf('\n========== CT NARX seed=%d ==========\n', s);
    rng(s);                          % fix weight initialization + data division

    net = narxnet(1:10, 1:10, 10, 'open', 'trainlm');
    [x, xi, ai, t] = preparets(net, X, {}, T);
    net.divideParam.trainRatio = 70/100;
    net.divideParam.valRatio   = 15/100;
    net.divideParam.testRatio  = 15/100;
    [net, tr] = train(net, x, t, xi, ai);

    varname = sprintf('CT_NARX_seed%d', s);
    S2.(varname) = struct('Network', net, 'TrainingResults', tr);
    save(fullfile(saveDir, sprintf('CT_NARX_seed%d.mat', s)), '-struct', 'S2');
    S2 = struct();
end
